config/routes.rb
Rails.application.routes.draw do
  root to: "quotes#index"
  resources :quotes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/quote.rb
class Quote < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: %i[ show edit update destroy ]

  def index
    @quotes = Quote.order("#{params[:column]} #{params[:direction]}")
  end

  def show
  end

  def new
    @quote = Quote.new
  end

  def edit
  end

  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully created." }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to quote_url(@quote), notice: "Quote was successfully updated." }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @quote.destroy

    respond_to do |format|
      format.html { redirect_to quotes_url, notice: "Quote was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_quote
    @quote = Quote.find(params[:id])
  end

  def quote_params
    params.require(:quote).permit(:quote, :character, :action)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
  def direction
    params[:direction] == "asc" ? "desc" : "asc"
  end

  def filter_arrow(column)
    if params[:column] == column
      if params[:direction] == "asc"
        "&#8659;".html_safe
      else
        "&#8657;".html_safe
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboFilterQuotes</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/_form.html.erb
<%= form_with(model: quote) do |form| %>
  <% if quote.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
        <% quote.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :quote, style: "display: block" %>
    <%= form.text_field :quote, class: "border px-2 py-1 rounded" %>
  </div>

  <div>
    <%= form.label :character, style: "display: block" %>
    <%= form.text_field :character, class: "border px-2 py-1 rounded" %>
  </div>

  <div>
    <%= form.label :action, style: "display: block" %>
    <%= form.text_field :action, class: "border px-2 py-1 rounded" %>
  </div>

  <div>
    <%= form.submit class: "underline" %>
  </div>
<% end %>

app/views/quotes/_quote.html.erb
<div>
  <p>
    <strong>Quote:</strong>
    <%= quote.quote %>
  </p>

  <p>
    <strong class="<%= "text-blue-500" if params[:column] == "character" %>">Character:</strong>
    <%= quote.character %>
  </p>

  <p>
    <strong class="<%= "text-teal-500" if params[:column] == "action" %>">Actor:</strong>
    <%= quote.action %>
  </p>

  <%= turbo_frame_tag dom_id(quote) do %>
    <%= link_to "Edit quote", edit_quote_path(quote), class: "underline" %>
  <% end %>
</div>

app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render "form", quote: @quote %>

<br>

<div>
  <%= link_to "Show this quote", @quote %> |
  <%= link_to "Back to quotes", quotes_path %>
</div>

app/views/quotes/index.html.erb
<div class="max-w-3xl mx-auto px-4 my-16">
  <div class="flex items-center justify-between pb-6 border-b dark:border-slate-700">
    <h1 class="font-bold text-3xl">Dumb and Dumber Quotes</h1>
    <div class="flex items-center justify-end">
      <%= link_to "New Quote", new_quote_path, class: "px-3 py-2 rounded bg-teal-500 hover:bg-teal-600 text-white" %>
    </div>
  </div>

  <%= turbo_frame_tag "quotes_data" do %>
    <div class="flex items-center p-3 bg-teal-600 text-white space-x-6 rounded">
      <%= link_to "Character", quotes_path(column: "character", direction: direction), class: "underline" %>
      <%= filter_arrow("character") %>
      <%= link_to "Actor", quotes_path(column: "action",  direction: direction), class: "underline" %>
      <%= filter_arrow("action") %>
      <%= link_to "Reset filter", quotes_path, class: "underline" %>
    </div>
    <div id="quotes" class="divide-y dark:text-slate-700 mb-10">
      <% @quotes.each do |quote| %>
        <div class="py-3">
          <%= render quote %>
          <%= link_to "View quote", quote_path(quote), class: "text-underline inline-block my-3", data: { turbo: false } %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render "form", quote: @quote %>

<br>

<div>
  <%= link_to "Back to quotes", quotes_path %>
</div>

app/views/quotes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @quote %>

<div>
  <%= link_to "Edit this quote", edit_quote_path(@quote) %> |
  <%= link_to "Back to quotes", quotes_path %>

  <%= button_to "Destroy this quote", @quote, method: :delete %>
</div>